# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72fd6d0a0bf4a90ce5654ae4a483453509a9be90965611f279d948c35bda4ffc61d20a9a6da529a3cc76c90cfff9f77c0e04b9d1d0e0f17907c0336f564e3c8e

test:
  secret_key_base: 699eafad0300e7b8f3e5447832f17895fba3f4f77188a68400e87d223c20271b20d374e3c5d5a43f92ad0a4de305035410a6313ef24da0c2af0e009fed678452

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
